@host = http://localhost:32774

### Create a new HiLo game
# @name createGame
POST {{host}}/games/hilo/
Content-Type: application/json

{
  "min": 1,
  "max": 100
}

###

@gameId = {{createGame.response.body.$.id}}

### Add players
# @name addPlayers
POST {{host}}/games/hilo/{{createGame.response.body.$.id}}/players
Content-Type: application/json

{
  "playerNames": ["Steve Jobs", "Bill Gates"]
}
###

@playerOneId = {{addPlayers.response.body.$.players[0].id}}
@playerTwoId = {{addPlayers.response.body.$.players[1].id}}

### Guess from Steve Jobs (Player 1)
POST {{host}}/games/hilo/{{{{gameId}}}}/players/{{{{playerOneId}}}}/guess
Content-Type: application/json

{
  "guess": 57
}
###

### Guess from Bill Gates (Player 2)
POST {{host}}/games/hilo/{{{{gameId}}}}/players/{{{{playerTwoId}}}}/guess
Content-Type: application/json

{
  "guess": 57
}
###