@host = https://localhost:32769

### Create a new HiLo game.
### Feel free to change the min and max values to test the game with different ranges.
# @name createGame
POST {{host}}/games/hilo/
Content-Type: application/json

{
  "min": 1,
  "max": 100
}

### Assign the game ID to a variable for later use.
@gameId = {{createGame.response.body.$.id}}

### Add a single player.
# @name addPlayers
POST {{host}}/games/hilo/{{gameId}}/players
Content-Type: application/json

{
  "playerNames": ["Mark Zuckerberg"]
}
###

@playerOneId = {{addPlayers.response.body.$.players[0].id}}

### Guess number.
### Feel free to change the guess value and repeat this request.
POST {{host}}/games/hilo/{{gameId}}/players/{{playerOneId}}/guess
Content-Type: application/json

{
  "guess": 34
}
###