@HiLoGame.Api_HostAddress = http://localhost:32768

### Create a new HiLo game
# @name createGame
POST {{HiLoGame.Api_HostAddress}}/games/hilo/
Content-Type: application/json

{
  "min": 1,
  "max": 100
}

###

### Add players
# @name addPlayers
POST {{HiLoGame.Api_HostAddress}}/games/hilo/{{createGame.response.body.$.id}}/players
Content-Type: application/json

{
  "playerNames": ["Mark Zuckerberg"]
}
###

### Guess number
POST {{HiLoGame.Api_HostAddress}}/games/hilo/{{createGame.response.body.$.id}}/players/{{addPlayers.response.body.$.playerTurn.id}}/guess
Content-Type: application/json

{
  "guess": 57
}
###