@host = https://localhost:32769

### Create a new HiLo game
# @name createGame
POST {{host}}/games/hilo/
Content-Type: application/json

{
  "min": 1,
  "max": 100
}

###

@gameId = {{createGame.response.body.$.id}}

### Add players
# @name addPlayers
POST {{host}}/games/hilo/{{gameId}}/players
Content-Type: application/json

{
  "playerNames": ["Mark Zuckerberg"]
}
###

@playerOneId = {{addPlayers.response.body.$.players[0].id}}

### Guess number
POST {{host}}/games/hilo/{{gameId}}/players/{{playerOneId}}/guess
Content-Type: application/json

{
  "guess": 34
}
###